version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=election
    depends_on:
      authenticationDB:
        condition: service_healthy
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=election
    depends_on:
      - authenticationDBMigration
    ports:
    - 5002:5002
  election:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  deamonDBMigration:
    image: deamondbmigration
    environment:
      - DATABASE_URL=election
    depends_on:
      - election
  deamon:
    image: deamon
    environment:
      - DATABASE_URL=election
    depends_on:
      - deamonDBMigration
